import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "~/lib/utils";
// import { ToastProvider } from "~/providers/toast-provider";
// import Navbar from "~/components/navbar";
import Header from "~/components/elements/header";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-w-screen relative h-full min-h-screen bg-background font-sans antialiased ",
          GeistSans.variable,
        )}
      >
        <main className="relative flex flex-col">
          <ClerkProvider
            appearance={{
              layout: {
                socialButtonsPlacement: "bottom",
                socialButtonsVariant: "blockButton",
              },
              variables: {
                colorPrimary: "#03449E",
                colorText: "#000000",
              },
            }}
          >
            <TRPCReactProvider>
              {/* <ToastProvider /> */}
              {/* <Navbar /> */}
              <Header />
              <div className="flex-1 flex-grow">{children}</div>
              <Toaster position="top-center" richColors />
            </TRPCReactProvider>
          </ClerkProvider>
        </main>
      </body>
    </html>
  );
}
